<a href="https://colab.research.google.com/github/povashraful/SOTA-Implementation/blob/main/Large%20Language%20Model%20from%20Scratch/Input_Target_pair.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
! pip3 install tiktoken

In [3]:
import importlib
import tiktoken

In [4]:
tokenizer = tiktoken.get_encoding("gpt2")

In [5]:
!wget "https://cnb.cool/8888/github.com/MLNLP-World/LLMs-from-scratch-CN/-/git/raw/8dc2f15e4cc3b68a30e74eedcf48387e32689e30/the-verdict.txt"


--2025-12-19 17:31:51--  https://cnb.cool/8888/github.com/MLNLP-World/LLMs-from-scratch-CN/-/git/raw/8dc2f15e4cc3b68a30e74eedcf48387e32689e30/the-verdict.txt
Resolving cnb.cool (cnb.cool)... 124.156.126.14
Connecting to cnb.cool (cnb.cool)|124.156.126.14|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: ‘the-verdict.txt’

the-verdict.txt         [ <=>                ]  20.16K  --.-KB/s    in 0.1s    

2025-12-19 17:31:52 (151 KB/s) - ‘the-verdict.txt’ saved [20643]



In [6]:
# with open("the-verdict.txt", "r", encoding="utf-8") as f: # r =reading
#     raw_text = f.read()

# print("Total number of character:", len(raw_text))
# print(raw_text[:99]) # prints the first 100 characters


#Syntax
# with open ("file_name", "r",encoding = "utf-8" ) as function_name:
#     object_name = function_name.read()

with open("the-verdict.txt", "r", encoding = "utf-8") as reading:
    raw_text = reading.read()

print("Total number of character:", len(raw_text))
print(raw_text[:99]) # prints the first 100 characters


Total number of character: 20479
I HAD always thought Jack Gisburn rather a cheap genius--though a good fellow enough--so it was no 


In [7]:
with open("the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

enc_text = tokenizer.encode(raw_text)
print(len(enc_text))

5145


In [8]:
enc_sample = enc_text[50:]


In [9]:
context_size = 10 #length of the input
#The context_size of 4 means that the model is trained to look at a sequence of 4 words (or tokens)
#to predict the next word in the sequence.
#The input x is the first 4 tokens [1, 2, 3, 4], and the target y is the next 4 tokens [2, 3, 4, 5]

x = enc_sample[:context_size]
y = enc_sample[1:context_size+1]

print(f"x: {x}")
print(f"y:      {y}")

x: [290, 4920, 2241, 287, 257, 4489, 64, 319, 262, 34686]
y:      [4920, 2241, 287, 257, 4489, 64, 319, 262, 34686, 41976]


In [10]:
for i in range(1, context_size+1):
    context = enc_sample[:i]
    desired = enc_sample[i]

    print(context, "---->", desired)

[290] ----> 4920
[290, 4920] ----> 2241
[290, 4920, 2241] ----> 287
[290, 4920, 2241, 287] ----> 257
[290, 4920, 2241, 287, 257] ----> 4489
[290, 4920, 2241, 287, 257, 4489] ----> 64
[290, 4920, 2241, 287, 257, 4489, 64] ----> 319
[290, 4920, 2241, 287, 257, 4489, 64, 319] ----> 262
[290, 4920, 2241, 287, 257, 4489, 64, 319, 262] ----> 34686
[290, 4920, 2241, 287, 257, 4489, 64, 319, 262, 34686] ----> 41976


In [11]:
for i in range(0, context_size+1):
    context = enc_sample[:i]
    desired = enc_sample[i]

    print(context, "---->", desired)

[] ----> 290
[290] ----> 4920
[290, 4920] ----> 2241
[290, 4920, 2241] ----> 287
[290, 4920, 2241, 287] ----> 257
[290, 4920, 2241, 287, 257] ----> 4489
[290, 4920, 2241, 287, 257, 4489] ----> 64
[290, 4920, 2241, 287, 257, 4489, 64] ----> 319
[290, 4920, 2241, 287, 257, 4489, 64, 319] ----> 262
[290, 4920, 2241, 287, 257, 4489, 64, 319, 262] ----> 34686
[290, 4920, 2241, 287, 257, 4489, 64, 319, 262, 34686] ----> 41976


In [12]:
for i in range(0, context_size+1):
    context = enc_sample[:i]
    desired = enc_sample[i]

    print(tokenizer.decode(context), "---->", tokenizer.decode([desired]))

 ---->  and
 and ---->  established
 and established ---->  himself
 and established himself ---->  in
 and established himself in ---->  a
 and established himself in a ---->  vill
 and established himself in a vill ----> a
 and established himself in a villa ---->  on
 and established himself in a villa on ---->  the
 and established himself in a villa on the ---->  Riv
 and established himself in a villa on the Riv ----> iera


In [13]:
for i in range(1, context_size+1):
    context = enc_sample[:i]
    desired = enc_sample[i]

    print(tokenizer.decode(context), "---->", tokenizer.decode([desired]))

 and ---->  established
 and established ---->  himself
 and established himself ---->  in
 and established himself in ---->  a
 and established himself in a ---->  vill
 and established himself in a vill ----> a
 and established himself in a villa ---->  on
 and established himself in a villa on ---->  the
 and established himself in a villa on the ---->  Riv
 and established himself in a villa on the Riv ----> iera


In [42]:
from torch.utils.data import Dataset, DataLoader


class text_dataset(Dataset):
    def __init__(self, txt, tokenizer, context_size_v1, stride):
      # stride = means how much we will shift - e.g. if stride is 1, we will shift right 1 word only.
      # text = the texts in our dataset
        self.input_ids = []  # we have create arrays
        self.target_ids = []

        # Tokenize the entire text
        token_ids = tokenizer.encode(txt, allowed_special={"<|endoftext|>"})

        # Use a sliding window to chunk the book into overlapping sequences of context_size_v1
        for i in range(0, len(token_ids) - context_size_v1, stride):
            input_chunk = token_ids[i:i + context_size_v1]
            # input_chuck will have token ids (0 to 4 {if our context size is 4})
            target_chunk = token_ids[i + 1: i + context_size_v1 + 1]
            # target_chunk will have token ids from 1 to 5 (slide 1)
            self.input_ids.append(torch.tensor(input_chunk))
            # appending / adding the input token ids to input_ids array
            self.target_ids.append(torch.tensor(target_chunk))
            # appending / adding the target token ids to input_ids array

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):

      # __getitem__ is a method
      # what it does is- based on the index we provide, it just returns that particular row of the input and that particular row of the output
      #for example, when index = 0, this will return the first row of the input tensor and first row of the output tensor.

      # the getitem method is needed for dataloader - to create input output pairs
        return self.input_ids[idx], self.target_ids[idx]

let us understand what is happening over here<br>

let us say, we have this in our dataset ->
<br>
"Hello my name is Tobias Rieper. I am really excited to start my jourey as a Master's student in Harvard. I have really worked hard for it and I am glad I got the admission"
<br><br>

now imagine, context size is 4 and stride = 1

loop 1:

input_chunk_1  = Hello my name is <br>
output_chunk_1 = my name is Tobias

<br><br>
loop 2:

input_chunk_2  = my name is Tobias <br>
output_chunk_2 = name is Tobias Rieper
<br><br>
loop 3:

input_chunk_3  = name is Tobias Rieper<br>
output_chunk_3 = is Tobias Rieper.

<br><br>
loop 4:

input_chunk_4  = is Tobias Rieper.<br>
output_chunk_4 = Tobias Rieper. I

<br><br>


<div class = "alert alert-block alert-warning"

In [43]:
def create_dataloader_v1(txt, batch_size=4, context_size_v1=256,
                         stride=128, shuffle=True, drop_last=True,
                         num_workers=0):
  #batch_size = how many batches (how many processes we want to run parallelly
  #by default it is 4)
  # context_size_v1 = gpt level context size - instead of just 4
  #stride =

  # num_of_workers = number of CPU threads we will run simultaneously


    # Initialize the tokenizer
    tokenizer = tiktoken.get_encoding("gpt2")

    # Create dataset

    # this is where we are doing the work
    dataset = text_dataset(txt, tokenizer, context_size_v1, stride)

    # Create dataloader
    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers
    )

    return dataloader

In [48]:
# first let us test our dataloader with smaller samples

In [44]:
with open("the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

In [62]:
import torch
print("PyTorch version:", torch.__version__)
dataloader = create_dataloader_v1(
    raw_text, batch_size=1, context_size_v1=4, stride=1, shuffle=False
)

data_iter = iter(dataloader)
first_batch = next(data_iter)
print(first_batch)

PyTorch version: 2.9.0+cpu
[tensor([[  40,  367, 2885, 1464]]), tensor([[ 367, 2885, 1464, 1807]])]


In [63]:
second_batch = next(data_iter)
print(second_batch)

[tensor([[ 367, 2885, 1464, 1807]]), tensor([[2885, 1464, 1807, 3619]])]


In [86]:
# let us what these numbers represents (this code is taken from ChatGPT)

import tiktoken

tokenizer = tiktoken.get_encoding("gpt2")

inputs, targets = first_batch

print("Input tokens:")
for tid in inputs[0]:
    print(f"{tid.item():>1} -> '{tokenizer.decode([tid.item()])}'")

print("\nTarget tokens:")
for tid in targets[0]:
    print(f"{tid.item():>1} -> '{tokenizer.decode([tid.item()])}'")


Input tokens:
40 -> 'I'
367 -> ' H'
2885 -> 'AD'
1464 -> ' always'

Target tokens:
367 -> ' H'
2885 -> 'AD'
1464 -> ' always'
1807 -> ' thought'


In [87]:
dataloader = create_dataloader_v1(raw_text, batch_size=8, context_size_v1=4, stride=4, shuffle=False)

data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print("Inputs:\n", inputs)
print("\nTargets:\n", targets)

Inputs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])

Targets:
 tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922],
        [ 5891,  1576,   438,   568],
        [  340,   373,   645,  1049],
        [ 5975,   284,   502,   284],
        [ 3285,   326,    11,   287]])


In [100]:
dataloader = create_dataloader_v1(raw_text, batch_size=8, context_size_v1=4, stride=4, shuffle=False)

data_iter = iter(dataloader)
inputs, targets = next(data_iter)
print("Inputs:\n", inputs)
print("\nTargets:\n", targets)

Inputs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])

Targets:
 tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922],
        [ 5891,  1576,   438,   568],
        [  340,   373,   645,  1049],
        [ 5975,   284,   502,   284],
        [ 3285,   326,    11,   287]])
